name: Label pull requests

on:
  pull_request:

jobs:
  label-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - run: brew developer on
      - run: brew update
      - run: brew deps --graph --include-build --include-test --dot watchman
